"""rename address

Revision ID: 0dd025b2bf43
Revises: 9d0f89257a7c
Create Date: 2025-08-29 01:09:22.849396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dd025b2bf43'
down_revision = '9d0f89257a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('address', sa.VARCHAR(), nullable=False))
    op.alter_column('departments', 'location', new_column_name='address')
    # ### end Alembic commands ###
